name: Close Stale Issues
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is stale and will be closed in 30 days unless new activity is seen.
          close-issue-message: >
            This issue was closed because it has been stalled for 30 days with no activity.
            Please feel free to re-open it is still a concern, possibly with additional data.
          stale-issue-label: 'stale'
          only-labels: 'awaiting%20answers'
          days-before-stale: 30
          days-before-close: 30