name: Close Stale Issues
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue is marked as stale and will be closed in 90 days unless new activity is seen.
          close-issue-message: >
            This issue was closed because it has been stalled for 90 days with no activity.
            Please feel free to reopen it if it is still a concern, possibly with additional data.
          stale-issue-label: 'stale'
          any-of-labels: 'awaiting answers,need info'
          days-before-stale: 20
          days-before-close: 90